version: '3.8'

services:

  postgres:
    container_name: postgres
    image: postgres:13.4
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - /var/opt/data/db:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '22181:2181'

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - '29092:29092'
    restart: always
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TOPIC_MAX_MESSAGE_BYTES: 10485760
      KAFKA_REPLICA_FETCH_MAX_BYTES: 10485760
      KAFKA_MESSAGE_MAX_BYTES: 10485760

  kafka-ui:
    image: provectuslabs/kafka-ui:master
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - '18080:8080'
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
      - KAFKA_CLUSTERS_0_READONLY=false

#  kafka-connect:
#    image: confluentinc/cp-kafka-connect:7.4.1.arm64
#    container_name: kafka-connect
#    ports:
#      - '8083:8083'
#    links:
#      - postgres:postgres
#      - kafka:kafka
#      - zookeeper:zookeeper
#    environment:
#      CONNECT_PLUGIN_PATH: '/usr/share/java,/usr/share/confluent-hub-components/'
#      LOG_LEVEL: DEBUG
#      CONNECT_ZOOKEEPER_CONNECT: zookeeper:2181
#      CONNECT_BOOTSTRAP_SERVERS: kafka:9092
#      CONNECT_GROUP_ID: pg-sink
#      CONNECT_CONFIG_STORAGE_TOPIC: connect-configs
#      CONNECT_STATUS_STORAGE_TOPIC: connect-status
#      CONNECT_OFFSET_STORAGE_TOPIC: connect-offsets
#      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
#      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
#      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
#      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
#      CONNECT_REST_PORT: 8083
#      CONNECT_REST_ADVERTISED_HOST_NAME: docker
#      CONNECT_SCHEMAS_ENABLE: 'false'
#      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: 'false'
#      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: 'false'